---

- name: download_install_metricbeat
  hosts: webservers
  become: yes
  tasks:
  - name: download_metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  - name: install_metricbeat
    command: sudo dpkg -i metricbeat-7.6.1-amd64.deb

  - name: drop
    copy:
      src: /etc/ansible/files/metricbeat_c_new.yml
      dest: /etc/metricbeat/metric.yml

  - name: enable
    command: metricbeat modules enable system

  - name: setup
    command: metricbeat setup

  - name: start
    command: service metricbeat start
