---

- name: config_vm_with_docker
  hosts: webservers
  become: true
  tasks:
  - name: docker.io
    apt:
      force_apt_get: yes
      update_cache: yes
      name: docker.io
      state: present

  - name: instal_pip3
    apt: 
      force_apt_get: yes
      name: python3-pip
      state: present

  - name: install_docker_python_module
    pip:
      name: docker
      state: present

  - name: download_and_launch_a_docker_web_container
    docker_container:
     name: dvwa
     image: cyberxsecurity/dvwa
     state: started
     published_ports: 80:80

  - name: enable_docker_service
    systemd:
       name: docker
       enabled: yes
